#pragma once

#include "misc/led.h"
#include "type.h"

extern const PaletteDataT DefaultCustomPalette_gp PROGMEM;

extern const PaletteDataT Abyss_p PROGMEM;
extern const PaletteDataT Aquatic_p PROGMEM;
extern const PaletteDataT Autumn_p PROGMEM;
extern const PaletteDataT Azure_p PROGMEM;
extern const PaletteDataT Bloom_p PROGMEM;
extern const PaletteDataT Blossom_p PROGMEM;
extern const PaletteDataT Blue_p PROGMEM;
extern const PaletteDataT Bonfire_p PROGMEM;
extern const PaletteDataT Cherry_p PROGMEM;
extern const PaletteDataT Cinnamon_p PROGMEM;
extern const PaletteDataT Coastal_p PROGMEM;
extern const PaletteDataT Cosmic_p PROGMEM;
extern const PaletteDataT Crimson_p PROGMEM;
extern const PaletteDataT Dawn_p PROGMEM;
extern const PaletteDataT DeepSea_p PROGMEM;
extern const PaletteDataT Deep_p PROGMEM;
extern const PaletteDataT Dreams_p PROGMEM;
extern const PaletteDataT Dusk_p PROGMEM;
extern const PaletteDataT Earthy_p PROGMEM;
extern const PaletteDataT Electric_p PROGMEM;
extern const PaletteDataT Elegance_p PROGMEM;
extern const PaletteDataT Emerald_p PROGMEM;
extern const PaletteDataT Enchanted_p PROGMEM;
extern const PaletteDataT Enigma_p PROGMEM;
extern const PaletteDataT Ethereal_p PROGMEM;
extern const PaletteDataT Fiery_p PROGMEM;
extern const PaletteDataT Flames_p PROGMEM;
extern const PaletteDataT Forest_p PROGMEM;
extern const PaletteDataT Golden_p PROGMEM;
extern const PaletteDataT Harmony_p PROGMEM;
extern const PaletteDataT Hush_p PROGMEM;
extern const PaletteDataT Infusion_p PROGMEM;
extern const PaletteDataT Jade_p PROGMEM;
extern const PaletteDataT Lavender_p PROGMEM;
extern const PaletteDataT Limeade_p PROGMEM;
extern const PaletteDataT Luminous_p PROGMEM;
extern const PaletteDataT MagicPlum_p PROGMEM;
extern const PaletteDataT Marine_p PROGMEM;
extern const PaletteDataT Meadow_p PROGMEM;
extern const PaletteDataT Midnight_p PROGMEM;
extern const PaletteDataT Minty_p PROGMEM;
extern const PaletteDataT Monochrome_p PROGMEM;
extern const PaletteDataT Moorland_p PROGMEM;
extern const PaletteDataT Mossy_p PROGMEM;
extern const PaletteDataT Mystic_p PROGMEM;
extern const PaletteDataT Neon_p PROGMEM;
extern const PaletteDataT Nightfall_p PROGMEM;
extern const PaletteDataT Nocturnal_p PROGMEM;
extern const PaletteDataT Oasis_p PROGMEM;
extern const PaletteDataT Ocean_p PROGMEM;
extern const PaletteDataT Oceanic_p PROGMEM;
extern const PaletteDataT Pastel_p PROGMEM;
extern const PaletteDataT RainbowShadow_p PROGMEM;
extern const PaletteDataT Rainbow_p PROGMEM;
extern const PaletteDataT Raspberry_p PROGMEM;
extern const PaletteDataT Scarlet_p PROGMEM;
extern const PaletteDataT Seaside_p PROGMEM;
extern const PaletteDataT Serenade_p PROGMEM;
extern const PaletteDataT Serene_p PROGMEM;
extern const PaletteDataT Serenity_p PROGMEM;
extern const PaletteDataT Slate_p PROGMEM;
extern const PaletteDataT Spice_p PROGMEM;
extern const PaletteDataT Splash_p PROGMEM;
extern const PaletteDataT Starlight_p PROGMEM;
extern const PaletteDataT Sultry_p PROGMEM;
extern const PaletteDataT Sunny_p PROGMEM;
extern const PaletteDataT Sunrise_p PROGMEM;
extern const PaletteDataT Sunset_p PROGMEM;
extern const PaletteDataT Tender_p PROGMEM;
extern const PaletteDataT Terrain_p PROGMEM;
extern const PaletteDataT Tranquil_p PROGMEM;
extern const PaletteDataT Tropics_p PROGMEM;
extern const PaletteDataT Twilight_p PROGMEM;
extern const PaletteDataT Urban_p PROGMEM;
extern const PaletteDataT Velvet_p PROGMEM;
extern const PaletteDataT Vintage_p PROGMEM;
extern const PaletteDataT Violet_p PROGMEM;
extern const PaletteDataT Woodland_p PROGMEM;

extern const std::initializer_list<PaletteEntry> palette_init;