#include "palette_def.h"

const std::initializer_list<PaletteEntry> palette_init = {
        {PaletteEnum::ABYSS,          "Abyss",          Abyss_p},
        {PaletteEnum::AQUATIC,        "Aquatic",        Aquatic_p},
        {PaletteEnum::AUTUMN,         "Autumn",         Autumn_p},
        {PaletteEnum::AZURE,          "Azure",          Azure_p},
        {PaletteEnum::BLOOM,          "Bloom",          Bloom_p},
        {PaletteEnum::BLOSSOM,        "Blossom",        Blossom_p},
        {PaletteEnum::BLUE,           "Blue",           Blue_p},
        {PaletteEnum::BONFIRE,        "Bonfire",        Bonfire_p},
        {PaletteEnum::CHERRY,         "Cherry",         Cherry_p},
        {PaletteEnum::CINNAMON,       "Cinnamon",       Cinnamon_p},
        {PaletteEnum::COASTAL,        "Coastal",        Coastal_p},
        {PaletteEnum::COSMIC,         "Cosmic",         Cosmic_p},
        {PaletteEnum::CRIMSON,        "Crimson",        Crimson_p},
        {PaletteEnum::DAWN,           "Dawn",           Dawn_p},
        {PaletteEnum::DEEP_SEA,       "Deep Sea",       DeepSea_p},
        {PaletteEnum::DEEP,           "Deep",           Deep_p},
        {PaletteEnum::DREAMS,         "Dreams",         Dreams_p},
        {PaletteEnum::DUSK,           "Dusk",           Dusk_p},
        {PaletteEnum::EARTHY,         "Earthy",         Earthy_p},
        {PaletteEnum::ELECTRIC,       "Electric",       Electric_p},
        {PaletteEnum::ELEGANCE,       "Elegance",       Elegance_p},
        {PaletteEnum::EMERALD,        "Emerald",        Emerald_p},
        {PaletteEnum::ENCHANTED,      "Enchanted",      Enchanted_p},
        {PaletteEnum::ENIGMA,         "Enigma",         Enigma_p},
        {PaletteEnum::ETHEREAL,       "Ethereal",       Ethereal_p},
        {PaletteEnum::FIERY,          "Fiery",          Fiery_p},
        {PaletteEnum::FLAMES,         "Flames",         Flames_p},
        {PaletteEnum::FOREST,         "Forest",         Forest_p},
        {PaletteEnum::GOLDEN,         "Golden",         Golden_p},
        {PaletteEnum::HARMONY,        "Harmony",        Harmony_p},
        {PaletteEnum::HUSH,           "Hush",           Hush_p},
        {PaletteEnum::INFUSION,       "Infusion",       Infusion_p},
        {PaletteEnum::JADE,           "Jade",           Jade_p},
        {PaletteEnum::LAVENDER,       "Lavender",       Lavender_p},
        {PaletteEnum::LIMEADE,        "Limeade",        Limeade_p},
        {PaletteEnum::LUMINOUS,       "Luminous",       Luminous_p},
        {PaletteEnum::MAGIC_PLUM,     "Magic Plum",     MagicPlum_p},
        {PaletteEnum::MARINE,         "Marine",         Marine_p},
        {PaletteEnum::MEADOW,         "Meadow",         Meadow_p},
        {PaletteEnum::MIDNIGHT,       "Midnight",       Midnight_p},
        {PaletteEnum::MINTY,          "Minty",          Minty_p},
        {PaletteEnum::MONOCHROME,     "Monochrome",     Monochrome_p},
        {PaletteEnum::MOORLAND,       "Moorland",       Moorland_p},
        {PaletteEnum::MOSSY,          "Mossy",          Mossy_p},
        {PaletteEnum::MYSTIC,         "Mystic",         Mystic_p},
        {PaletteEnum::NEON,           "Neon",           Neon_p},
        {PaletteEnum::NIGHTFALL,      "Nightfall",      Nightfall_p},
        {PaletteEnum::NOCTURNAL,      "Nocturnal",      Nocturnal_p},
        {PaletteEnum::OASIS,          "Oasis",          Oasis_p},
        {PaletteEnum::OCEAN,          "Ocean",          Ocean_p},
        {PaletteEnum::OCEANIC,        "Oceanic",        Oceanic_p},
        {PaletteEnum::PASTEL,         "Pastel",         Pastel_p},
        {PaletteEnum::RAINBOW_SHADOW, "Rainbow Shadow", RainbowShadow_p},
        {PaletteEnum::RAINBOW,        "Rainbow",        Rainbow_p},
        {PaletteEnum::RASPBERRY,      "Raspberry",      Raspberry_p},
        {PaletteEnum::SCARLET,        "Scarlet",        Scarlet_p},
        {PaletteEnum::SEASIDE,        "Seaside",        Seaside_p},
        {PaletteEnum::SERENADE,       "Serenade",       Serenade_p},
        {PaletteEnum::SERENE,         "Serene",         Serene_p},
        {PaletteEnum::SERENITY,       "Serenity",       Serenity_p},
        {PaletteEnum::SLATE,          "Slate",          Slate_p},
        {PaletteEnum::SPICE,          "Spice",          Spice_p},
        {PaletteEnum::SPLASH,         "Splash",         Splash_p},
        {PaletteEnum::STARLIGHT,      "Starlight",      Starlight_p},
        {PaletteEnum::SULTRY,         "Sultry",         Sultry_p},
        {PaletteEnum::SUNNY,          "Sunny",          Sunny_p},
        {PaletteEnum::SUNRISE,        "Sunrise",        Sunrise_p},
        {PaletteEnum::SUNSET,         "Sunset",         Sunset_p},
        {PaletteEnum::TENDER,         "Tender",         Tender_p},
        {PaletteEnum::TERRAIN,        "Terrain",        Terrain_p},
        {PaletteEnum::TRANQUIL,       "Tranquil",       Tranquil_p},
        {PaletteEnum::TROPICS,        "Tropics",        Tropics_p},
        {PaletteEnum::TWILIGHT,       "Twilight",       Twilight_p},
        {PaletteEnum::URBAN,          "Urban",          Urban_p},
        {PaletteEnum::VELVET,         "Velvet",         Velvet_p},
        {PaletteEnum::VINTAGE,        "Vintage",        Vintage_p},
        {PaletteEnum::VIOLET,         "Violet",         Violet_p},
        {PaletteEnum::WOODLAND,       "Woodland",       Woodland_p},

        {PaletteEnum::CUSTOM,         "Custom",         DefaultCustomPalette_gp},
};