#pragma once

#include <cctype>

enum class PacketType : uint8_t {
    //PARAMETERS

    SPEED = 0,
    SCALE = 1,
    LIGHT = 2,

    MAX_BRIGHTNESS = 20,
    ECO_LEVEL = 21,
    GAMMA = 22,

    NIGHT_MODE_ENABLED = 40,
    NIGHT_MODE_START = 41,
    NIGHT_MODE_END = 42,
    NIGHT_MODE_INTERVAL = 43,
    NIGHT_MODE_BRIGHTNESS = 44,
    NIGHT_MODE_ECO = 45,

    AUDIO_ENABLED = 50,
    AUDIO_EFFECT = 51,
    AUDIO_SIGNAL_GAIN = 52,
    AUDIO_SIGNAL_GATE = 53,

    PRESET_ID = 60,
    PRESET_NAME = 61,

    UPDATE_CUSTOM_PALETTE = 70,

    UPDATE_PRESET_NAMES = 80,
    UPDATE_PRESET_CONFIGS = 81,

    PALETTE = 100,
    COLOR_EFFECT = 101,
    BRIGHTNESS_EFFECT = 102,

    // CALIBRATION

    CALIBRATION_R = 120,
    CALIBRATION_G = 121,
    CALIBRATION_B = 122,

    // LISTS

    PALETTE_LIST = 140,
    COLOR_EFFECT_LIST = 141,
    BRIGHTNESS_EFFECT_LIST = 142,
    PRESET_NAMES_LIST = 143,
    PRESET_CONFIG_LIST = 144,

    GET_CONFIG = 160,
    GET_PRESET_CONFIG = 161,

    GET_PALETTE = 180,

    // COMMANDS

    DISCOVERY = 200,

    POWER_OFF = 220,
    POWER_ON = 221,
    RESTART = 222,
};